public enum TokenType {
    // Keywords
    SUGOD, KATAPUSAN, MUGNA, IPAKITA, DAWAT,
    KUNG, KUNG_WALA, KUNG_DILI, ALANG_SA, PUNDOK,

    // Types
    NUMERO, LETRA, TINUOD, TIPIK,

    // Literals
    IDENTIFIER, NUMBER, STRING, CHAR, BOOLEAN_TRUE, BOOLEAN_FALSE,

    // Operators & Symbols
    ASSIGN, PLUS, MINUS, STAR, SLASH, PERCENT, COLON, SQUARE_BRACKETS,
    COMMA, SINGLE_QUOTE, AMPERSAND, DOLLAR, LBRACE, RBRACE, LPAREN, RPAREN,

    // Logical
    UG, O, DILI,

    COMMENT, NEWLINE, ESCAPE_SEQUENCE, EOF
}
